### ISSUE TITLE
For bham groups

### ISSUE THREAD

**Issue by LattVines** [wad3g/bhamtech#6]
please add a link to the facebook page for the bham gamedev group: 
https://www.facebook.com/groups/bhamgamedev/

We are very loosely organized but meet on the 3rd thursday each month at the UAB business and engineering building.

We also have a slack channel where users share resources and sometimes work together on projects.
bhamgamedevs.slack.com

**Comment by wad3g** [comment]
@LattVines Do you have a link so you can sign up for the Slack channel? I'd rather not get into the habit of adding private Slack channels.

**Comment by LattVines** [comment]
good call. I sent an invite.

**Comment by wad3g** [comment]
added Facebook & Slack links
